version: '0.2'

phases:
  install:
    runtime-versions:
      nodejs: '18'
    commands:
      # - echo "Updating npm to the latest version..."
      # - npm install -g npm@latest
      - pwd
      - ls -lah
      - echo "Installing dependencies..."
      - cd infra && npm install --include=dev
      - npm install -g typescript
      - echo "Verifying TypeScript installation..."
      - tsc --version
      - pwd
      - cd ../..

      # --- Lambdas ---
      - echo "== Install all lambdas =="
      - if [ -d lambdas ]; then
          cd lambdas;
          for d in */ ; do
            if [ -f "$d/package.json" ]; then
              echo "Installing in lambdas/$d";
              (cd "$d" && npm ci);
            fi;
          done;
          cd ..;
        else
          echo "No lambdas directory found, skipping.";
        fi
  build:
    commands:
      - cd ../..
      # --- Build lambdas ---
      - echo "== Build all lambdas =="
      - if [ -d lambdas ]; then
          cd lambdas;
          for d in */ ; do
            if [ -f "$d/package.json" ]; then
              echo "Building lambdas/$d";
              (cd "$d" && npm run build);
            fi;
          done;
          cd ..;
        else
          echo "No lambdas directory found, skipping.";
        fi
      - echo "Synthesizing CDK..."
      - cd infra
      - npx cdk synth  --context env=dev --verbose
      - npx cdk deploy --all --context env=dev --require-approval never
artifacts:
  files:
    - '**/*'
  base-directory: infra/dist
